### PR TITLE
Adding Terratest code to test IaC

### PR DESCRIPTION
**Pull request by imnitin28**
As discussed in day 62 under Testing, Tools & Alternatives. I have done some work in terratest to write code to do automated test for IaC.

### CODE REVIEW

**Comment by MichaelCade** [comment]
Does this make sense to merge still? None of the files created here seem to be linked in the readme?

**Comment by MichaelCade** [comment]
We should link this on day62.md as a resource to learn more about testing with terratest. 

Fantastic work! Sorry it has taken this long to re look at the PR. It's been a very hectic year.

**Comment by imnitin28** [comment]
Hi @MichaelCade. Thanks!
Hope you are doing great. Thanks!
I have raised a new PR with these additions and day 62 updated. https://github.com/MichaelCade/90DaysOfDevOps/pull/263

**Comment by MichaelCade** [comment]
Close with newer pull request now in play.

**Pull request closed without merging**
