### PR TITLE
repeated line

### PR DESCRIPTION
**Pull request by souravsk**
In the Listing Resources table, the last row is repeated

### CODE REVIEW

**Comment by souravsk** [comment]
can you please help me? what should I do so that it won't get fail next time when contributing to your project

**Comment by MichaelCade** [comment]
Hey there thanks for contributing. Don’t worry about that fail it is based on tweeting the PR which I need to look at.

**Comment by Tecnophille** [comment]
If you don't mind, send me a message on WhatsApp +2347055453641

**Comment by souravsk** [comment]
Yes why not but can i know the reason

**Comment by MichaelCade** [comment]
You don’t have access to my secrets in GitHub which has the API key to Twitter. Only maintainers will have a successful merge test there.

**Comment by souravsk** [comment]
Thanku Michael for explaining

**Pull request merged**
