### PR TITLE
Merge main to gh_pages for web-app to include 2023 edition

### PR DESCRIPTION
**Pull request by rishabkumar7**
Merging `main` to `gh_pages` to include 2023 edition in web-app

### CODE REVIEW

**Comment by MichaelCade** [comment]
@rishabkumar7 do you need me to do anything here?

**Comment by rishabkumar7** [comment]
@MichaelCade yeah, not sure why there are conflicts in the `2022` edition, were these changed?

**Comment by MichaelCade** [comment]
A lot of these seem to be the 2024 edition updates. We are still getting update PRs to both 2022 and 2023.

**Comment by rishabkumar7** [comment]
Talked to @MichaelCade about the website, we won't be having individual markdown files on the web platform, so this PR is invalid.

**Pull request closed without merging**
