### PR TITLE
Navigation each day

### LINKED ISSUE #373: Navigation each day
In 2022 I finished everyday with a link to the following day, this is something I want to add when the 2023 edition is complete. 

PR started https://github.com/MichaelCade/90DaysOfDevOps/pull/372

### PR DESCRIPTION
**Pull request by codesmiles**
Been able to update the navigation for each day close #373

### CODE REVIEW

**Comment by MichaelCade** [comment]
Thanks for this, saved me a job.

**Comment by codesmiles** [comment]
Ya no problem, I kinda noticed that some days are blank are they to be filled later or are the just there for strategic reasons?

**Comment by codesmiles** [comment]
> Thanks for this, saved me a job.
You're welcome sir

**Comment by codesmiles** [comment]
You're welcome

**Pull request merged**
