### PR TITLE
Translated 2022 day35-55 to korean 

### PR DESCRIPTION
**Pull request by Me1e**

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
Hi @Me1e, Can you squash your commits?

**Comment by Me1e** [comment]
> Hi @Me1e, Can you squash your commits?

Hi! Thank you for reviewing my commit.
Working with squash is not difficult, but if you don't mind me asking, could you tell me why I should work with squash?
I ask simply because I want to learn the open source ecosystem :)

**Comment by shivam-sharma7** [comment]
> > Hi @Me1e, Can you squash your commits?
> 
> Hi! Thank you for reviewing my commit. Working with squash is not difficult, but if you don't mind me asking, could you tell me why I should work with squash? I ask simply because I want to learn the open source ecosystem :)

Squashing commits allows you to create a clean, concise commit history. Instead of having multiple small commits that may not make sense on their own, you can combine them into one meaningful commit that tells a story

**Comment by Me1e** [comment]
> > > Hi @Me1e, Can you squash your commits?
> > 
> > 
> > Hi! Thank you for reviewing my commit. Working with squash is not difficult, but if you don't mind me asking, could you tell me why I should work with squash? I ask simply because I want to learn the open source ecosystem :)
> 
> Squashing commits allows you to create a clean, concise commit history. Instead of having multiple small commits that may not make sense on their own, you can combine them into one meaningful commit that tells a story

I don't know if I did a good job, but I did squash all the commits!
Thanks for the review :)

**Pull request merged**
