### PR TITLE
Fixed all footeer/bottom links

### PR DESCRIPTION
**Pull request by Taiwrash**
Fixing #349 

Let me know how it goes

### CODE REVIEW

**Comment by MichaelCade** [comment]
Will this break the navigation on the GitHub repository but would fix for the website?

**Comment by Taiwrash** [comment]
@MichaelCade just confirmed it breaks the navigation on GitHub.

Thoughts 🤔
Can we deploy separate branch as website to fix this?

But if I can find a fix for both I will try to get it done. Thanks

**Comment by MichaelCade** [comment]
Yes we have created another branch

**Comment by MichaelCade** [comment]
We have created a new branch, myself and @rishabkumar7 are working on moving the website to this branch leaving the original in place.

**Comment by Taiwrash** [comment]
Oh nice, will look into that soon...

**Comment by MichaelCade** [comment]
This has now been completed for 2022 on the GitHub Pages branch, 2023 and translations are being completed. I am sure @rishabkumar7 would take some help on that front. 

I will now close this PR

**Pull request closed without merging**
