### PR TITLE
vi - added day 7 - 11 content

### PR DESCRIPTION
**Pull request by qmau94**

### CODE REVIEW

**Comment by MichaelCade** [comment]
@qmau94 What is the purpose here? Are you adding changes to the existing or is this you documenting your own journey? If the latter then please fork the repository and add your own journey there. I don't want to change my notes or files

**Comment by qmau94** [comment]
@MichaelCade 

I have added all your files (images, examples,...) to the vi folder. The only addition is the screenshot of this pop-up on day 8 for better understanding. 

image

> I don't want to change my notes or files

I think it is fair. I will delete the added screenshot if you want. 
Other than that, no changes/additions were made.

**Comment by qmau94** [comment]
@MichaelCade 

I have added all your files (images, examples,...) to the vi folder. 

The only addition I made is the screenshot of this pop-up on day 8. 

image

> I don't want to change my notes or files

It is fair, I will delete the added screenshot :) 
This PR has no changes/additions other than the translation.

**Comment by MichaelCade** [comment]
This PR is wanting to merge into the main repository?

**Comment by qmau94** [comment]
@MichaelCade yup, also deleted assets and examples as I can refer them from your folder

**Pull request merged**
