### PR TITLE
90DaysOfDevOps 2024 - day 35

### PR DESCRIPTION
**Pull request by patrickkusebauch**
Using code dependency analysis to decide what to test

### CODE REVIEW

**Comment by MichaelCade** [comment]
I will merge this when we get to the day of release for the video

**Comment by MichaelCade** [comment]
Hey @patrickkusebauch We are going to move your day to the 15th Jan. Could you please take day15.md for your blog/notes please for the audience. Sorry to put this on you but sessions have not been submitted in time so appreciate your efforts on getting your session in.

**Comment by patrickkusebauch** [comment]
@MichaelCade you got it!

**Comment by MichaelCade** [comment]
@patrickkusebauch I have made the change to the agenda, your session will now be day15 so the 15th Jan it will go up. Thank you for this move.

**Pull request merged**
